// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#include <algorithm>
#include <string_view>

namespace Core::HostRuntime {
// Explicit compatibility surface: desktop LibcInternal HLE registrations plus
// standard guest stream/runtime exports used by production content. This grants
// lookup only; Bind still requires a unique guest libc function in an executable
// ELF segment. It never grants a host function pointer or arbitrary NID alias.
struct GuestLibcEntry { std::string_view nid, name, family; };
inline constexpr GuestLibcEntry GuestLibcEntries[]{
    {"dhK16CKwhQg", "__isfinite", "math"},
    {"V02oFv+-JzA", "__isinf", "math"},
    {"GfxAp9Xyiqs", "__isnan", "math"},
    {"JrwFIMzKNr0", "ldexp", "math"},
    {"ZtjspkJQ+vw", "_FSin", "math"},
    {"iz2shAGFIxc", "hypotf", "math"},
    {"VOBg+iNwB-4", "strtoll", "runtime"},
    {"MELi-cKqWq0", "_ZSt19_Xbad_function_callv", "runtime"},
    {"AEJdIVZTEmo", "qsort", "runtime"},
    {"3BytPOQgVKc", "snprintf_s", "io"},
    {"xGT4Mc55ViQ", "_Fofind", "io"},
    {"jVDuvE3s5Bs", "_Fofree", "io"},
    {"sQL8D-jio7U", "_Fopen", "io"},
    {"dREVnZkAKRE", "_Foprep", "io"},
    {"9s3P+LCvWP8", "_Frprep", "io"},
    {"A+Y3xfrWLLo", "_Fspos", "io"},
    {"vZkmJmvqueY", "_Lockfilelock", "io"},
    {"Ss3108pBuZY", "_Nnl", "io"},
    {"0x7rx8TKy2Y", "_Unlockfilelock", "io"},
    {"St9nbxSoezk", "clearerr", "io"},
    {"uodLYyUip20", "fclose", "io"},
    {"LxcEU+ICu8U", "feof", "io"},
    {"AHxyhN96dy4", "ferror", "io"},
    {"MUjC4lbHrK4", "fflush", "io"},
    {"AEuF3F2f8TA", "fgetc", "io"},
    {"SHlt7EhOtqA", "fgetpos", "io"},
    {"KdP-nULpuGw", "fgets", "io"},
    {"Fm-dmyywH9Q", "fileno", "io"},
    {"xeYO4u7uyJ0", "fopen", "io"},
    {"NL836gOLANs", "fopen_s", "io"},
    {"fffwELXNVFA", "fprintf", "io"},
    {"aZK8lNei-Qw", "fputc", "io"},
    {"QrZZdJ8XsX0", "fputs", "io"},
    {"lbB+UlZqVG0", "fread", "io"},
    {"gkWgn0p1AfU", "freopen", "io"},
    {"rQFVBXp-Cxg", "fseek", "io"},
    {"pkYiKw09PRA", "fseeko", "io"},
    {"7PkSz+qnTto", "fsetpos", "io"},
    {"Qazy8LmXTvw", "ftell", "io"},
    {"5qP1iVQkdck", "ftello", "io"},
    {"MpxhMh8QFro", "fwrite", "io"},
    {"8Q60JLJ6Rv4", "getc", "io"},
    {"L3XZiuKqZUM", "getchar", "io"},
    {"EMutwaQ34Jo", "perror", "io"},
    {"hcuQgD53UxM", "printf", "io"},
    {"tLB5+4TEOK0", "putc", "io"},
    {"m5wN+SwZOR4", "putchar", "io"},
    {"YQ0navp+YIc", "puts", "io"},
    {"3QIPIh-GDjw", "rewind", "io"},
    {"vZMcAfsA31I", "setbuf", "io"},
    {"QMFyLoqNxIg", "setvbuf", "io"},
    {"eLdDw6l0-bU", "snprintf", "io"},
    {"tcVi5SivF7Q", "sprintf", "io"},
    {"-LFO7jhD5CE", "ungetc", "io"},
    {"pDBDcY6uLSA", "vfprintf", "io"},
    {"GMpvxPFW924", "vprintf", "io"},
    {"Q2V+iqvjgC0", "vsnprintf", "io"},
    {"jbz9I9vkqkk", "vsprintf", "io"},
    {"JBcgYuW8lPU", "acos", "math"},
    {"QI-x0SL8jhw", "acosf", "math"},
    {"7Ly52zaL44Q", "asin", "math"},
    {"GZWjF-YIFFk", "asinf", "math"},
    {"OXmauLdQ8kY", "atan", "math"},
    {"HUbZmOnT-Dg", "atan2", "math"},
    {"EH-x713A99c", "atan2f", "math"},
    {"weDug8QD-lE", "atanf", "math"},
    {"2WE3BTYVwKM", "cos", "math"},
    {"-P6FNMzk2Kc", "cosf", "math"},
    {"NVadfnzQhHQ", "exp", "math"},
    {"dnaeGXbjP6E", "exp2", "math"},
    {"wuAQt-j+p4o", "exp2f", "math"},
    {"8zsu04XNsZ4", "expf", "math"},
    {"rtV7-jWC6Yg", "log", "math"},
    {"WuMbPBKN1TU", "log10", "math"},
    {"lhpd6Wk6ccs", "log10f", "math"},
    {"RQXLbdT2lc4", "logf", "math"},
    {"9LCjpWyQ5Zc", "pow", "math"},
    {"1D0H2KNjshE", "powf", "math"},
    {"H8ya2H00jbI", "sin", "math"},
    {"jMB7EFyu30Y", "sincos", "math"},
    {"pztV4AF18iI", "sincosf", "math"},
    {"Q4rRL34CEeE", "sinf", "math"},
    {"T7uyNqP7vQA", "tan", "math"},
    {"ZE6RNL+eLbk", "tanf", "math"},
    {"DfivPArhucg", "memcmp", "memory"},
    {"Q3VBxCXhUHs", "memcpy", "memory"},
    {"NFLs+dRJGNg", "memcpy_s", "memory"},
    {"8zTFvBIAIN8", "memset", "memory"},
    {"+P6FRGH4LfA", "memmove", "memory"},
    {"fJnpuVVBbKk", "_Znwm", "runtime"},
    {"sUP1hBaouOw", "_Getpctype", "runtime"},
    {"7pNKcscKrf8", "_Stoll", "runtime"},
    // Keep C++ static initialization and allocation inside the same guest libc
    // as the consuming plug-in. Never substitute host guards or host pointers.
    {"3GPpjQdAMTw", "__cxa_guard_acquire", "runtime"},
    {"9rAeANT2tyE", "__cxa_guard_release", "runtime"},
    {"2emaaluWzUw", "__cxa_guard_abort", "runtime"},
    {"k04jLXu3+Ic", "sceLibcMspaceMallocStatsFast", "runtime"},
    {"zlfEH8FmyUA", "_Stoul", "runtime"},
    {"z+P+xCnWLBk", "_ZdlPv", "runtime"},
    {"tsvEmnenz48", "__cxa_atexit", "runtime"},
    {"H2e8t5ScQGc", "__cxa_finalize", "runtime"},
    {"zr094EQ39Ww", "__cxa_pure_virtual", "runtime"},
    {"L1SBTkC+Cvw", "abort", "runtime"},
    {"tIhsqj0qsFE", "free", "runtime"},
    {"1mecP7RgI2A", "gmtime", "runtime"},
    {"5bBacGLyLOs", "gmtime_s", "runtime"},
    {"efhK-YSUYYQ", "localtime", "runtime"},
    {"gQX+4GDQjpM", "malloc", "runtime"},
    {"n7AepwR0s34", "mktime", "runtime"},
    {"-hn1tcVHq5Q", "sceLibcMspaceCreate", "runtime"},
    {"W6SiVSiCDtI", "sceLibcMspaceDestroy", "runtime"},
    {"Vla-Z+eXlxo", "sceLibcMspaceFree", "runtime"},
    {"OJjm-QOIHlI", "sceLibcMspaceMalloc", "runtime"},
    {"mfHdJTIvhuo", "sceLibcMspaceMallocStats", "runtime"},
    {"gigoVHZvVPE", "sceLibcMspaceRealloc", "runtime"},
    {"kHg45qPC6f0", "strncat", "runtime"},
    {"viiwFMaNamA", "strstr", "runtime"},
    {"wLlFkwG9UcQ", "time", "runtime"},
    {"Ls4tzzhimqQ", "strcat", "str"},
    {"K+gcnFFJKVc", "strcat_s", "str"},
    {"ob5xAW4ln-0", "strchr", "str"},
    {"Ovb2dSJOAuE", "strcmp", "str"},
    {"5Xa2ACNECdo", "strcpy_s", "str"},
    {"j4ViWNHEgww", "strlen", "str"},
    {"aesyjrHVWy4", "strncmp", "str"},
    {"6sJWiWSRuqk", "strncpy", "str"},
    {"YNzNkJzYqEg", "strncpy_s", "str"},
    {"LaPaA6mYA38", "_Mtxdst", "threads"},
    {"z7STeF6abuU", "_Mtxinit", "threads"},
    {"pE4Ot3CffW0", "_Mtxlock", "threads"},
    {"cMwgSSmpE5o", "_Mtxunlock", "threads"},
};
inline bool IsGuestLibcFunction(std::string_view nid) {
    return std::any_of(std::begin(GuestLibcEntries), std::end(GuestLibcEntries),
                       [nid](const auto& entry) { return entry.nid == nid; });
}
} // namespace Core::HostRuntime
