// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#include <functional>
#include "core/guest_cpu/api/address_space.h"
#include "guest_storage.h"
namespace Core::HostRuntime {
enum class StorageOp {
    SetupMemory2, GetMemory2, SetMemory2, SyncMemory, TransferringMount,
    SetupMemory,
    GetMemory,
    SetMemory,
    SaveIcon,
    Search,
    UnmountBackup,
    CheckBackup,
    RestoreBackup,
    Delete,
    Event,
    Init,
    Term,
    Mount,
    Mount2,
    Unmount,
    Info,
    GetParam,
    SetParam,
    Open,
    Close,
    Read,
    Write,
    Seek,
    Sync,
    Mkdir,
    Rmdir,
    Unlink,
    Rename,
    CheckReachability,
    Stat,
    Fstat,
    GetDents,
    GetDirEntries,
    Pread,
    Pwrite,
    Preadv,
    Pwritev,
    Truncate
};
struct StorageEntry {
    std::string_view nid;
    StorageOp op;
    bool save;
    bool posix{};
};
inline constexpr StorageEntry StorageEntries[]{
    {"oQySEUfgXRA", StorageOp::SetupMemory2, true},
    {"QwOO7vegnV8", StorageOp::GetMemory2, true},
    {"cduy9v4YmT4", StorageOp::SetMemory2, true},
    {"wiT9jeC7xPw", StorageOp::SyncMemory, true},
    {"WAzWTZm1H+I", StorageOp::TransferringMount, true},
    {"uWyW3v98sU4", StorageOp::CheckReachability, false},
    {"naInUjYt3so", StorageOp::Rmdir, false},
    {"c7ZnT7V1B98", StorageOp::Rmdir, false, true},
    {"v7AAAMo0Lz4", StorageOp::SetupMemory, true},
    {"7Bt5pBC-Aco", StorageOp::GetMemory, true},
    {"h3YURzXGSVQ", StorageOp::SetMemory, true},
    {"c88Yy54Mx0w", StorageOp::SaveIcon, true},
    {"dyIhnXq-0SM", StorageOp::Search, true},
{"j2AIqSqJP0w", StorageOp::GetDents, false},
                                               {"2G6i6hMIUUY", StorageOp::GetDents, false, true},
                                               {"taRWhTJFTgE", StorageOp::GetDirEntries, false},
                                               {"sfKygSjIbI8", StorageOp::GetDirEntries, false, true},
                                               {"eV9wAD2riIA", StorageOp::Stat, false},
                                               {"E6ao34wPw+U", StorageOp::Stat, false, true},
                                               {"kBwCPsYX-m4", StorageOp::Fstat, false},
                                               {"mqQMh1zPPT8", StorageOp::Fstat, false, true},
                                               {"+r3rMFwItV4", StorageOp::Pread, false},
                                               {"ezv-RSBNKqI", StorageOp::Pread, false, true},
                                               {"nKWi-N2HBV4", StorageOp::Pwrite, false},
                                               {"C2kJ-byS5rM", StorageOp::Pwrite, false, true},
                                               {"yTj62I7kw4s", StorageOp::Preadv, false},
                                               {"mBd4AfLP+u8", StorageOp::Pwritev, false},
                                               {"FCcmRZhWtOk", StorageOp::Pwritev, false, true},
                                               {"VW3TVZiM4-E", StorageOp::Truncate, false},
                                               {"ih4CD9-gghM", StorageOp::Truncate, false, true},
                                               {"juWbTNM+8hw", StorageOp::Sync, false, true},
                                               {"VAzswvTOCzI", StorageOp::Unlink, false, true},
                                               {"NN01qLRhiqU", StorageOp::Rename, false, true},
                                               {"VwadwBBBJ80", StorageOp::UnmountBackup, true},
                                               {"RQOqDbk3bSU", StorageOp::CheckBackup, true},
                                               {"lU9YRFsgwSU", StorageOp::RestoreBackup, true},
                                               {"S1GkePI17zQ", StorageOp::Delete, true},
                                               {"j8xKtiFj0SY", StorageOp::Event, true},
                                               {"ZkZhskCPXFw", StorageOp::Init, true},
                                               {"l1NmDeDpNGU", StorageOp::Init, true},
                                               {"TywrFKCoLGY", StorageOp::Init, true},
                                               {"yKDy8S5yLA0", StorageOp::Term, true},
                                               {"32HQAQdwM2o", StorageOp::Mount, true},
                                               {"0z45PIH+SNI", StorageOp::Mount2, true},
                                               {"BMR4F-Uek3E", StorageOp::Unmount, true},
                                               {"65VH0Qaaz6s", StorageOp::Info, true},
                                               {"XgvSuIdnMlw", StorageOp::GetParam, true},
                                               {"85zul--eGXs", StorageOp::SetParam, true},
                                               {"1G3lF1Gg1k8", StorageOp::Open, false},
                                               {"6c3rCVE-fTU", StorageOp::Open, false, true},
                                               {"wuCroIGjt2g", StorageOp::Open, false, true},
                                               {"UK2Tl2DWUns", StorageOp::Close, false},
                                               {"NNtFaKJbPt0", StorageOp::Close, false, true},
                                               {"bY-PO6JhzhQ", StorageOp::Close, false, true},
                                               {"Cg4srZ6TKbU", StorageOp::Read, false},
                                               {"DRuBt2pvICk", StorageOp::Read, false, true},
                                               {"AqBioC2vF3I", StorageOp::Read, false, true},
                                               {"4wSze92BhLI", StorageOp::Write, false},
                                               {"FxVZqBAA7ks", StorageOp::Write, false, true},
                                               {"FN4gaPmuFV8", StorageOp::Write, false, true},
                                               {"oib76F-12fk", StorageOp::Seek, false},
                                               {"Oy6IpwgtYOk", StorageOp::Seek, false, true},
                                               {"fTx66l5iWIA", StorageOp::Sync, false},
                                               {"1-LFLmRFxxM", StorageOp::Mkdir, false},
                                               {"JGMio+21L4c", StorageOp::Mkdir, false, true},
                                               {"AUXVxWeJU-A", StorageOp::Unlink, false},
                                               {"52NcYU9+lEo", StorageOp::Rename, false}};
u64 DispatchStorage(GuestStorage& storage, GuestCpu::GuestAddressSpace& space,
                    const StorageEntry& entry, const std::array<u64, 6>& args,
                    const std::function<u64(int)>& posix_failure);
} // namespace Core::HostRuntime
