// SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#include <array>
#include <fstream>
#include <map>
#include <span>
#include <openssl/evp.h>
#include <openssl/rsa.h>
#include <openssl/sha.h>
#include <zlib.h>
#include "core/crypto/crypto.h"
#include "core/crypto/keys.h"
#include "core/file_format/psf.h"

// Synthetic FPKGs, created independently of the production reader. The fixtures
// contain only generated bytes; signed-32 outer PFS, unsigned-32 inner PFS,
// independently zlib-compressed blocks and sector XTS exercise the real parser.
namespace PkgFixture {
using Bytes = std::vector<u8>;
constexpr size_t Block = 65536;
inline void Put(Bytes& data, size_t at, u64 value, size_t size, bool big = false) {
    for (size_t i = 0; i < size; ++i)
        data.at(at + i) = value >> (8 * (big ? size - i - 1 : i));
}
inline void Copy(Bytes& out, size_t at, std::span<const u8> bytes) {
    std::copy(bytes.begin(), bytes.end(), out.begin() + at);
}
inline void Dirent(Bytes& out, size_t& at, u32 inode, u32 type, const std::string& name) {
    const size_t record = (16 + name.size() + 7) & ~size_t{7};
    Put(out, at, inode, 4);
    Put(out, at + 4, type, 4);
    Put(out, at + 8, name.size(), 4);
    Put(out, at + 12, record, 4);
    std::copy(name.begin(), name.end(), out.begin() + at + 16);
    at += record;
}
inline Bytes Pfs(const std::map<std::string, Bytes>& files, bool signed_nodes) {
    size_t blocks = 4;
    for (const auto& [_, bytes] : files)
        blocks += (bytes.size() + Block - 1) / Block;
    Bytes out(blocks * Block);
    Put(out, 0, 1, 8);
    Put(out, 8, 20130315, 8);
    Put(out, 0x1c, signed_nodes ? 13 : 8, 2);
    Put(out, 0x20, Block, 4);
    Put(out, 0x28, 1, 8);
    Put(out, 0x30, files.size() + 2, 8);
    Put(out, 0x40, 1, 8);
    const auto inode = [&](size_t id, bool directory, size_t bytes, size_t first) {
        const size_t at = Block + id * (signed_nodes ? 0x2c8 : 0xa8);
        Put(out, at, directory ? 0x416d : 0x816d, 2);
        Put(out, at + 2, 1, 2);
        Put(out, at + 8, bytes, 8);
        Put(out, at + 16, bytes, 8);
        Put(out, at + 0x60, (bytes + Block - 1) / Block, 4);
        Put(out, at + (signed_nodes ? 0x84 : 0x64), first, 4);
        Put(out, at + (signed_nodes ? 0xa8 : 0x68), UINT32_MAX, 4);
    };
    inode(0, true, Block, 2);
    inode(1, true, Block, 3);
    size_t root = 2 * Block;
    Dirent(out, root, 1, 3, "uroot");
    size_t dir = 3 * Block, first = 4, id = 2;
    for (const auto& [name, bytes] : files) {
        inode(id, false, bytes.size(), first);
        Dirent(out, dir, id++, 2, name);
        Copy(out, first * Block, bytes);
        first += (bytes.size() + Block - 1) / Block;
    }
    return out;
}
inline Bytes Pfsc(const Bytes& image) {
    const size_t count = image.size() / Block;
    Bytes out(0x30 + (count + 1) * 8);
    Put(out, 0, 0x43534650, 4);
    Put(out, 8, 6, 4);
    Put(out, 12, Block, 4);
    Put(out, 16, Block, 8);
    Put(out, 24, 0x30, 8);
    Put(out, 32, out.size(), 8);
    Put(out, 40, image.size(), 8);
    for (size_t i = 0; i < count; ++i) {
        Put(out, 0x30 + i * 8, out.size(), 8);
        Bytes compressed(compressBound(Block));
        uLongf length = compressed.size();
        if (compress2(compressed.data(), &length, image.data() + i * Block, Block, 6) != Z_OK)
            throw std::runtime_error("fixture zlib");
        if (length >= Block)
            out.insert(out.end(), image.begin() + i * Block, image.begin() + (i + 1) * Block);
        else
            out.insert(out.end(), compressed.begin(), compressed.begin() + length);
    }
    Put(out, 0x30 + count * 8, out.size(), 8);
    return out;
}
template <class Key>
inline std::array<u8, 256> Wrap(const std::array<u8, 32>& input) {
    auto* key = RSA_new();
    RSA_set0_key(key, BN_bin2bn(Key::Modulus, sizeof(Key::Modulus), nullptr),
                 BN_bin2bn(Key::PublicExponent, sizeof(Key::PublicExponent), nullptr), nullptr);
    std::array<u8, 256> out{};
    const int size =
        RSA_public_encrypt(input.size(), input.data(), out.data(), key, RSA_PKCS1_PADDING);
    RSA_free(key);
    if (size != 256)
        throw std::runtime_error("fixture RSA");
    return out;
}
inline void Make(const std::filesystem::path& path, const std::map<std::string, Bytes>& files,
                 std::string category = "gd", std::string title = "CUSA99999",
                 std::string label = "SYNTHETIC0000000", std::string version = "01.00",
                 bool sparse = false) {
    Bytes head(65536);
    const u64 pfs_offset = sparse ? 0x100010000ULL : head.size();
    auto outer = Pfs({{"pfs_image.dat", Pfsc(Pfs(files, false))}}, true);
    std::array<u8, 32> dk3{}, ekpfs{};
    std::array<u8, 16> seed{}, data{}, tweak{};
    for (size_t i = 0; i < 32; ++i) {
        dk3[i] = u8(i + 1);
        ekpfs[i] = u8(i + 65);
    }
    for (size_t i = 0; i < 16; ++i)
        seed[i] = u8(i + 129);
    Copy(outer, 0x370, seed);
    Core::Crypto::PfsGenCryptoKey(ekpfs, seed, data, tweak);
    std::array<u8, 32> key{};
    std::copy(data.begin(), data.end(), key.begin());
    std::copy(tweak.begin(), tweak.end(), key.begin() + 16);
    auto* ctx = EVP_CIPHER_CTX_new();
    for (size_t at = Block; at < outer.size(); at += 4096) {
        std::array<u8, 16> iv{};
        u64 sector = at / 4096;
        for (size_t i = 0; i < 8; ++i)
            iv[i] = sector >> (8 * i);
        int written = 0;
        if (EVP_EncryptInit_ex(ctx, EVP_aes_128_xts(), nullptr, key.data(), iv.data()) != 1 ||
            EVP_EncryptUpdate(ctx, outer.data() + at, &written, outer.data() + at, 4096) != 1 ||
            written != 4096)
            throw std::runtime_error("fixture XTS");
    }
    EVP_CIPHER_CTX_free(ctx);
    PSF sfo;
    sfo.AddString("TITLE_ID", title);
    sfo.AddString("TITLE", "Synthetic package");
    sfo.AddString("CONTENT_ID", "UP0000-" + title + "_00-" + label);
    sfo.AddString("CATEGORY", category);
    sfo.AddString("APP_VER", version);
    const auto metadata = sfo.Encode();
    Put(head, 0, 0x7f434e54, 4, true);
    Put(head, 4, 0x40000001, 4, true);
    Put(head, 0x10, 3, 4, true);
    Put(head, 0x18, 0x2000, 4, true);
    Put(head, 0x410, pfs_offset, 8, true);
    Put(head, 0x418, outer.size(), 8, true);
    Put(head, 0x430, pfs_offset + outer.size(), 8, true);
    auto entry = [&](size_t i, u32 id, u32 offset, u32 size) {
        Put(head, 0x2000 + 32 * i, id, 4, true);
        Put(head, 0x2010 + 32 * i, offset, 4, true);
        Put(head, 0x2014 + 32 * i, size, 4, true);
    };
    entry(0, 0x10, 0x4000, 0x800);
    entry(1, 0x20, 0x4800, 0x100);
    entry(2, 0x1000, 0x5000, metadata.size());
    Copy(head, 0x4000 + 0x20 + 7 * 0x20 + 3 * 0x100, Wrap<PkgDerivedKey3Keyset>(dk3));
    std::array<u8, 64> hash_input{};
    std::copy_n(head.begin() + 0x2020, 32, hash_input.begin());
    std::copy(dk3.begin(), dk3.end(), hash_input.begin() + 32);
    std::array<u8, 32> ivkey{};
    SHA256(hash_input.data(), hash_input.size(), ivkey.data());
    auto encrypted = Wrap<FakeKeyset>(ekpfs);
    ctx = EVP_CIPHER_CTX_new();
    int written = 0;
    EVP_EncryptInit_ex(ctx, EVP_aes_128_cbc(), nullptr, ivkey.data() + 16, ivkey.data());
    EVP_CIPHER_CTX_set_padding(ctx, 0);
    if (EVP_EncryptUpdate(ctx, head.data() + 0x4800, &written, encrypted.data(),
                          encrypted.size()) != 1 ||
        written != 256)
        throw std::runtime_error("fixture CBC");
    EVP_CIPHER_CTX_free(ctx);
    Copy(head, 0x5000, metadata);
    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::binary);
    out.write(reinterpret_cast<const char*>(head.data()), head.size());
    out.seekp(pfs_offset);
    out.write(reinterpret_cast<const char*>(outer.data()), outer.size());
    if (!out)
        throw std::runtime_error("fixture write");
}
} // namespace PkgFixture
