#!/usr/bin/env python3
"""Generate Opcodes.g.cs from the emulator's GCN decoder tables.

Opcode names come from src/shader_recompiler/frontend/opcodes.h and operand counts from
src/shader_recompiler/frontend/format.cpp, so the disassembler agrees with the recompiler on what
every encoding value means. Operand widths are decided in Operands.cs (format.cpp records a single
type per instruction, which is not precise for mixed-width instructions). Re-run after either file
changes:

    python tools/gcn-disasm/gen_opcodes.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
FRONTEND = ROOT / "src" / "shader_recompiler" / "frontend"
TARGET = pathlib.Path(__file__).resolve().parent / "Opcodes.g.cs"

# Encoding -> table size (range of the encoding's opcode field).
ENCODINGS = {
    "SOP2": 128, "SOPK": 32, "SOP1": 256, "SOPC": 128, "SOPP": 128, "SMRD": 32,
    "VOP2": 64, "VOP1": 256, "VOPC": 256, "VOP3": 1024, "VOP3P": 128, "VINTRP": 4,
    "DS": 256, "MUBUF": 128, "MTBUF": 8, "MIMG": 128, "EXP": 1,
}


def names_of(text, encoding, size):
    match = re.search(rf"enum class Opcode{encoding} : u32 \{{(.*?)\}};", text, re.S)
    if not match:
        raise SystemExit(f"enum Opcode{encoding} not found")
    names = [None] * size
    for entry in re.finditer(r"^\s*(\w+)\s*=\s*(\d+)", match.group(1), re.M):
        name, value = entry.group(1), int(entry.group(2))
        if not name.startswith("OP_RANGE") and value < size and names[value] is None:
            names[value] = name.lower()  # First spelling wins (V_CMP_TRU_F32 over V_CMP_T_F32).
    return names


def counts_of(text, encoding, size):
    match = re.search(rf"InstructionFormat{encoding} = ", text)
    if not match:
        return [None] * size
    # The initializer is one balanced brace block; each table entry is a brace group without
    # nested groups ({} for a hole), however many aggregate braces wrap the list.
    body = re.sub(r"//[^\n]*", "", text[match.end():])
    counts = [None] * size
    index, stack = 0, []
    for pos, char in enumerate(body):
        if char == "{":
            if stack:
                stack[-1][1] = True
            stack.append([pos, False])
        elif char == "}":
            start, has_child = stack.pop()
            if not has_child:
                fields = [f.strip() for f in body[start + 1:pos].split(",")]
                if len(fields) >= 4 and fields[2].isdigit() and index < size:
                    counts[index] = (int(fields[2]), int(fields[3]))
                index += 1
            if not stack:
                break
    return counts


def main():
    opcodes = (FRONTEND / "opcodes.h").read_text(encoding="utf-8")
    formats = (FRONTEND / "format.cpp").read_text(encoding="utf-8")
    lines = [
        "// <auto-generated> by tools/gcn-disasm/gen_opcodes.py from",
        "// src/shader_recompiler/frontend/opcodes.h and format.cpp. Do not edit.</auto-generated>",
        "#nullable enable",
        "namespace GcnDisasm;",
        "",
        "internal static class OpcodeTables {",
    ]
    for encoding, size in ENCODINGS.items():
        names = names_of(opcodes, encoding, size)
        counts = counts_of(formats, encoding, size)
        body = ", ".join("null" if n is None else f'"{n}"' for n in names)
        lines.append(f"    public static readonly string?[] {encoding} = [{body}];")
        # Source/destination operand counts packed as src | dst << 4; 0xff when unknown.
        packed = ", ".join("0xff" if c is None else f"0x{c[0] | c[1] << 4:02x}" for c in counts)
        lines.append(f"    public static readonly byte[] {encoding}Counts = [{packed}];")
    lines.append("}")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
