#!/system/bin/sh
set -eu
umask 022
D=/data/local/tmp/litep_kgsl_10609aa25307
I=/sys/kernel/tracing/instances/kgsl_dbg_10609aa25307
exec > "$D/control.log" 2>&1
[ "$(id -u)" = 0 ]
[ ! -e "$I" ]
[ "$(cat /proc/sys/kernel/random/boot_id)" = 8bb14501-5800-4b9b-a9ab-7173603812f7 ]
mkdir "$I"
trap 'echo 0 > "$I/tracing_on"' EXIT
printf 0 > "$I/tracing_on"
cp /sys/kernel/tracing/tracing_on "$D/global-tracing-before.txt"
cp /sys/kernel/tracing/trace_clock "$D/global-clock-before.txt"
cp /sys/kernel/tracing/buffer_total_size_kb "$D/global-buffer-before.txt"
# Allocate across all trace buffers, including offline CPUs.
N=$(ls -d "$I"/per_cpu/cpu* | wc -l)
K=$((384 * 1024 / N))
A=$(awk '/MemAvailable:/ {print $2}' /proc/meminfo)
[ "$((A-K*N))" -ge 1572864 ]
echo "$K" > "$I/buffer_size_kb"
echo mono > "$I/trace_clock"
echo 1 > "$I/options/overwrite"
for O in record-cmd record-tgid; do
 if [ -e "$I/options/$O" ]; then echo 1 > "$I/options/$O"; fi
done
cat "$I/trace_clock" > "$D/trace-clock.txt"
cat "$I/buffer_total_size_kb" > "$D/buffer-total-kib.txt"
: > "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_context_create/enable"
echo "[kgsl:kgsl_context_create]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_context_create/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_context_destroy/enable"
echo "[kgsl:kgsl_context_destroy]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_context_destroy/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_context_detach/enable"
echo "[kgsl:kgsl_context_detach]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_context_detach/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_issueibcmds/enable"
echo "[kgsl:kgsl_issueibcmds]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_issueibcmds/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_queued/enable"
echo "[kgsl:adreno_cmdbatch_queued]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_queued/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_ready/enable"
echo "[kgsl:adreno_cmdbatch_ready]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_ready/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_submitted/enable"
echo "[kgsl:adreno_cmdbatch_submitted]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_submitted/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_done/enable"
echo "[kgsl:adreno_cmdbatch_done]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_done/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_retired/enable"
echo "[kgsl:adreno_cmdbatch_retired]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_retired/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_sync/enable"
echo "[kgsl:adreno_cmdbatch_sync]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_sync/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_fault/enable"
echo "[kgsl:adreno_cmdbatch_fault]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_fault/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_cmdbatch_recovery/enable"
echo "[kgsl:adreno_cmdbatch_recovery]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_cmdbatch_recovery/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_drawctxt_switch/enable"
echo "[kgsl:adreno_drawctxt_switch]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_drawctxt_switch/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_preempt_trigger/enable"
echo "[kgsl:adreno_preempt_trigger]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_preempt_trigger/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_preempt_done/enable"
echo "[kgsl:adreno_preempt_done]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_preempt_done/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_waittimestamp_entry/enable"
echo "[kgsl:kgsl_waittimestamp_entry]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_waittimestamp_entry/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_waittimestamp_exit/enable"
echo "[kgsl:kgsl_waittimestamp_exit]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_waittimestamp_exit/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_drawctxt_wait_start/enable"
echo "[kgsl:adreno_drawctxt_wait_start]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_drawctxt_wait_start/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_drawctxt_wait_done/enable"
echo "[kgsl:adreno_drawctxt_wait_done]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_drawctxt_wait_done/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/adreno_gpu_fault/enable"
echo "[kgsl:adreno_gpu_fault]" >> "$D/formats.txt"
cat "$I/events/kgsl/adreno_gpu_fault/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_mmu_pagefault/enable"
echo "[kgsl:kgsl_mmu_pagefault]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_mmu_pagefault/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_gpubusy/enable"
echo "[kgsl:kgsl_gpubusy]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_gpubusy/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_pwrlevel/enable"
echo "[kgsl:kgsl_pwrlevel]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_pwrlevel/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/gpu_frequency/enable"
echo "[kgsl:gpu_frequency]" >> "$D/formats.txt"
cat "$I/events/kgsl/gpu_frequency/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/kgsl_pwrstats/enable"
echo "[kgsl:kgsl_pwrstats]" >> "$D/formats.txt"
cat "$I/events/kgsl/kgsl_pwrstats/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/syncpoint_fence/enable"
echo "[kgsl:syncpoint_fence]" >> "$D/formats.txt"
cat "$I/events/kgsl/syncpoint_fence/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/syncpoint_fence_expire/enable"
echo "[kgsl:syncpoint_fence_expire]" >> "$D/formats.txt"
cat "$I/events/kgsl/syncpoint_fence_expire/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/syncpoint_timestamp/enable"
echo "[kgsl:syncpoint_timestamp]" >> "$D/formats.txt"
cat "$I/events/kgsl/syncpoint_timestamp/format" >> "$D/formats.txt"
echo 1 > "$I/events/kgsl/syncpoint_timestamp_expire/enable"
echo "[kgsl:syncpoint_timestamp_expire]" >> "$D/formats.txt"
cat "$I/events/kgsl/syncpoint_timestamp_expire/format" >> "$D/formats.txt"
echo 1 > "$I/events/sched/sched_switch/enable"
echo "[sched:sched_switch]" >> "$D/formats.txt"
cat "$I/events/sched/sched_switch/format" >> "$D/formats.txt"
echo 1 > "$I/events/sched/sched_waking/enable"
echo "[sched:sched_waking]" >> "$D/formats.txt"
cat "$I/events/sched/sched_waking/format" >> "$D/formats.txt"
echo 1 > "$I/events/sched/sched_wakeup/enable"
echo "[sched:sched_wakeup]" >> "$D/formats.txt"
cat "$I/events/sched/sched_wakeup/format" >> "$D/formats.txt"
echo 1 > "$I/events/power/cpu_frequency/enable"
echo "[power:cpu_frequency]" >> "$D/formats.txt"
cat "$I/events/power/cpu_frequency/format" >> "$D/formats.txt"
if [ -e "$I/events/kgsl/adreno_gpu_fault/trigger" ]; then echo traceoff > "$I/events/kgsl/adreno_gpu_fault/trigger"; fi
cat /proc/719/stat > "$D/process-before.txt"
ls /proc/719/task > "$D/tids.txt"
for T in /proc/719/task/*; do echo "$T"; cat "$T/comm"; done > "$D/thread-names.txt"
cat /proc/sys/kernel/random/boot_id > "$D/boot-id.txt"
cat /sys/class/kgsl/kgsl-3d0/gpu_model > "$D/gpu-model.txt" 2>/dev/null || true
uname -a > "$D/kernel.txt"
getprop ro.build.fingerprint > "$D/fingerprint.txt"
echo 1 > "$I/tracing_on"
"$D/clock" "$I/trace_marker" start > "$D/anchor-start.txt"
echo armed > "$D/status"
sleep 26
"$D/clock" "$I/trace_marker" end > "$D/anchor-end.txt"
echo 0 > "$I/tracing_on"
for F in "$I"/per_cpu/cpu*/stats; do echo "[$F]"; cat "$F"; done > "$D/per-cpu-stats.txt"
cat /proc/719/stat > "$D/process-after.txt"
cat "$I/trace" | gzip -1 > "$D/kgsl_trace.txt.gz"
cp /sys/kernel/tracing/tracing_on "$D/global-tracing-after.txt"
cp /sys/kernel/tracing/trace_clock "$D/global-clock-after.txt"
cp /sys/kernel/tracing/buffer_total_size_kb "$D/global-buffer-after.txt"
chmod 644 "$D"/*
echo collected > "$D/status"
