# SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later
include_guard(GLOBAL)

# Shared recipes for the desktop externals and the Android dependency build.
# Dependency options stay in this function/subdirectory, not the host/FEX scope.
function(shadps4_add_host_portable_dependency name)
    get_filename_component(deps "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../externals" ABSOLUTE)
    set(out "${CMAKE_CURRENT_BINARY_DIR}/${name}")
    if(name STREQUAL "glslang")
        if(NOT TARGET glslang::glslang)
            set(SKIP_GLSLANG_INSTALL ON CACHE BOOL "")
            set(ENABLE_GLSLANG_BINARIES OFF CACHE BOOL "")
            set(ENABLE_SPVREMAPPER OFF CACHE BOOL "")
            set(ENABLE_CTEST OFF CACHE BOOL "")
            set(ENABLE_HLSL OFF CACHE BOOL "")
            set(BUILD_EXTERNAL OFF CACHE BOOL "")
            set(ENABLE_OPT OFF CACHE BOOL "")
            add_subdirectory("${deps}/glslang" "${out}")
            file(COPY "${deps}/glslang/SPIRV" DESTINATION "${out}/glslang" FILES_MATCHING PATTERN "*.h")
            target_include_directories(glslang INTERFACE "${out}")
        endif()
    elseif(name STREQUAL "zydis")
        if(NOT TARGET Zydis::Zydis)
            option(ZYDIS_BUILD_TOOLS "" OFF)
            option(ZYDIS_BUILD_EXAMPLES "" OFF)
            add_subdirectory("${deps}/zydis" "${out}")
        endif()
    elseif(name STREQUAL "date")
        if(NOT TARGET date::date-tz)
            option(BUILD_TZ_LIB "" ON)
            option(USE_SYSTEM_TZ_DB "" ON)
            add_subdirectory("${deps}/date" "${out}")
        endif()
    elseif(name STREQUAL "miniz")
        if(NOT TARGET miniz::miniz)
            add_subdirectory("${deps}/miniz" "${out}")
            add_library(miniz::miniz ALIAS miniz)
        endif()
    elseif(name STREQUAL "libressl")
        if(TARGET LibreSSL::SSL OR TARGET LibreSSL::Crypto)
            set(libs LibreSSL::SSL LibreSSL::Crypto)
        elseif(TARGET OpenSSL::SSL OR TARGET OpenSSL::Crypto)
            set(libs OpenSSL::SSL OpenSSL::Crypto)
        else()
            set(LIBRESSL_SKIP_INSTALL ON CACHE BOOL "" FORCE)
            set(LIBRESSL_APPS OFF CACHE BOOL "" FORCE)
            set(LIBRESSL_TESTS OFF CACHE BOOL "" FORCE)
            add_subdirectory("${deps}/libressl" "${out}" EXCLUDE_FROM_ALL)
            get_directory_property(libs DIRECTORY "${deps}/libressl" DEFINITION OPENSSL_LIBS)
        endif()
        set(SSL_DEPENDENCIES "${libs}" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unknown portable host dependency: ${name}")
    endif()
endfunction()
